let x = Buffer('1234567890')
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())
console.log(x.slice(0,1).toString())